PARAMS_ENUM = {
    "bothify": [str, str],
    "lexify": [str, str],
    "numerify": [str],
    "random_int": [int, int, int],
    "random_number": [int, bool],
    "country_code": [str],
    "ean": [int],
    "localized_ean": [int],
    "color": [str, str, str],
    "credit_card_full": [str],
    "credit_card_number": [str],
    "credit_card_provider": [str],
    "credit_card_security_code": [str],
    "date": [str],
    "time": [str],
    "file_extension": [str],
    "file_name": [str, str],
    "file_path": [int, str, str],
    "mime_type": [str],
    "unix_device": [str],
    "unix_partition": [str],
    "domain_name": [int],
    "email": [str],
    "hostname": [int],
    "image_url": [int, int],
    "ipv4": [bool, str, bool],
    "ipv4_private": [bool, str],
    "ipv4_public": [bool, str],
    "ipv6": [bool],
    "uri_path": [int],
    "isbn10": [str],
    "isbn13": [str],
    "paragraph": [int, bool],
    "paragraphs": [int],
    "sentence": [int, bool],
    "sentences": [int],
    "text": [int],
    "texts": [int, int],
    "word": [int],
    "words": [int],
    "password": [int, bool, bool, bool, bool],
    "pyfloat": [int, int, bool],
    "loadfile": [str],
    "b64encode_str": [str],
    "b64encode_bytes": [bytes],
    "b64encode_file": [str],
    "b64decode_toStr": [str],
    "b64decode_toBytes": [str],
    "arithmetic": [str],
    "current_time": [str],
    "year_shift": [float, str],
    "month_shift": [float, str],
    "week_shift": [float, str],
    "date_shift": [float, str],
    "hour_shift": [float, str],
    "minute_shift": [float, str],
    "second_shift": [float, str],
    "indexof": [list, int],
    "keyof": [dict, str],
    "pinyin": [str],
    "substing": [str, int, int],
    "extract": [str],
    "replace": [str, str, str],
    "map_dumps": [dict],
    "array_dumps": [list],
}
